### ISSUE TITLE
test_callback_1

### ISSUE THREAD

**Issue by mjuenema** [mjuenema/python-sigfox-backend-api#8]
Works on my PC but not on Travis-CI
```
======================================================================
ERROR: test_sigfoxapi.TestSigfoxCallbacks.test_callback_1_enable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.3/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/mjuenema/python-sigfox-backend-api/tests/test_sigfoxapi.py", line 232, in test_callback_1_enable
    self.s.callback_enable(SIGFOX_DEVICETYPE_ID, CALLBACKID)
  File "/home/travis/build/mjuenema/python-sigfox-backend-api/sigfoxapi/__init__.py", line 514, in callback_enable
    (devicetypeid, callbackid))
  File "/home/travis/build/mjuenema/python-sigfox-backend-api/sigfoxapi/__init__.py", line 171, in request
    raise SigfoxApiBadRequest(str(e))
sigfoxapi.SigfoxApiBadRequest: Received HTTP Code 400 - Bad Request
-------------------- >> begin captured stdout << ---------------------
DREST_DEBUG: method=POST url=https://backend.sigfox.com/api/devicetypes/[secure]/callbacks/None/enable?enabled=true params={} headers={'Content-Type': 'application/json'}
```

**Comment by mjuenema** [comment]
This is a follow-on error to #7 which must set the `CALLBACK_ID` global variable.
